name = "EmeraldPipelines"
uuid = "ed2140b8-dfe6-4b4c-b3f6-273f81b97561"
version = "0.1.0"
authors = ["Yujie Wang <jesiner@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Emerald = "56ca4449-d59c-41e3-9ae8-0f89b45aadb6"
GriddingMachine = "f20cf718-bf4d-4727-bc8f-485b1f283ac6"
NetcdfIO = "6a36f34d-89cf-423a-87c4-84549e82f670"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
NetcdfIO = "0.2.11"
OrderedCollections = "1.8.1"
